Test_of_tea/urls.py
from django.contrib import admin
from django.urls import path, include

from main_page.views import main_view, tea_cards_view, about_view, teashop_view, testimonies_view, contact_us_view
from accounts.views import registration_view, login_view, logout_view

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', main_view),
    path('services/', tea_cards_view),
    path('about/', about_view),
    path('teashop/', teashop_view),
    path('testimonies/', testimonies_view),
    path('contact/', contact_us_view),
    path('registration/', registration_view, name='registration'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('manager/', include('manager.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

manager/urls.py
from django.urls import path
from .views import contact_us_message_list, update_message

app_name = 'manager'

urlpatterns = [
    path('messages/', contact_us_message_list, name='messages'),
    path('messages/update/<int:pk>/', update_message, name='update_message')
]

manager/models.py
from django.db import models

# Create your models here.

manager/views.py
from django.shortcuts import render, redirect
from main_page.models import Contact_us_form
from django.contrib.auth.decorators import login_required

# Create your views here.


@login_required(login_url='/login/')
def contact_us_message_list(request):
    messages = Contact_us_form.objects.filter(is_processed=False)

    return render(request, 'contact_us_message_list.html', context={'messages': messages})


@login_required(login_url='/login/')
def update_message(request, pk):
    Contact_us_form.objects.filter(pk=pk).update(is_processed=True)
    return redirect('manager:messages')

manager/templates/contact_us_message_list.html
{% extends 'index.html' %}

{% block main_content %}

<div class="container">
    <h2>Messages from users</h2>
    <hr>
    {% for message in messages %}
        <div class="request-item">
            <h4>{{ message.name }}</h4>
            <p>{{ message.phone }}</p>
            <p>{{ message.message }}</p>
            <p>{{ message.email }}</p>
            <a href="{% url 'manager:update_message' pk=message.pk %}" class="btn btn-primary">Message processed</a>
        </div>
    {% empty %}
        <p>No message found.</p>
    {% endfor %}
</div>

{% endblock %}